spring.application.name=sintonia

spring.datasource.url=jdbc:postgresql://localhost:5432/sintonia
spring.datasource.username=postgres
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.defer-datasource-initialization=true

spring.sql.init.mode=always

youtube.api-key=${YOUTUBE_API_KEY:}
youtube.base-url=https://www.googleapis.com/youtube/v3