package br.com.sintonia.websocket;

public enum RoomEventType {
    PLAYBACK_STARTED,
    PLAYBACK_FINISHED,
    PLAYBACK_SKIPPED,
    PLAYBACK_ERROR,
    PLAYBACK_PAUSED,
    PLAYBACK_RESUMED,
    QUEUE_CHANGED,
    PLAYER_CHANGED,
    PLAYBACK_MODE_CHANGED,
    SKIP_VOTE_CHANGED
}